# project-root/docker-compose.yml
version: '3'
services:
  client:
    build: ./client
    container_name: client
    restart: always

  server:
    build: ./server
    container_name: server
    restart: always
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./server/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
      - prometheus
      - grafana
