# project-root/docker-compose.yml
version: '3'
services:
  client:
    build: ./client
    container_name: client
    restart: always

  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "5000:5000"  # only if you want external access
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./server/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
      - prometheus
      - grafana
